# -*- coding: utf-8 -*-
"""Electrochemistry Fuel cell - scikit.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aTmeEVWjr2-XU2GcdQd2tScRiScuorwZ
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import shap
import joblib
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import GroupKFold, GridSearchCV
from sklearn.inspection import permutation_importance

df1 = pd.read_csv('/content/pem-dataset1/Standard Test of Nafion Membrane 112/1.csv')
df2 = pd.read_csv('/content/pem-dataset1/Standard Test of Nafion Membrane 112/2.csv')

X = df[['current_density', 'pressure', 'relative_humidity', 'membrane_compression']]
y = df['cell_voltage']

groups = (df['pressure'].astype(str) + '_' +
          df['relative_humidity'].astype(str) + '_' +
          df['membrane_compression'].astype(str))

print(f"Unique operating conditions (groups): {groups.nunique()}")
counts = groups.value_counts()
print(f"Points per curve: min={counts.min()}, "
      f"median={int(counts.median())}, max={counts.max()}")

assert groups.nunique() >= 5, "Need >=5 unique groups for GroupKFold(n_splits=5)"

param_grid = {
    'n_estimators':     [300, 600],
    'max_depth':        [None, 15],
    'min_samples_leaf': [1, 2],
    'max_features':     ['sqrt', 1.0],
}

# n_jobs=1 on the estimator; GridSearchCV does the parallelizing
base_rf = RandomForestRegressor(random_state=42, n_jobs=1)

grid = GridSearchCV(
    estimator=base_rf,
    param_grid=param_grid,
    cv=GroupKFold(n_splits=5),
    scoring='r2',
    n_jobs=-1,
    verbose=2,            # bumped to 2 so you can see progress in Colab
    refit=True,
)

grid.fit(X, y, groups=groups)

print(f"\nBest GroupKFold R^2: {grid.best_score_:.4f}")
print("Best params:")
for k, v in grid.best_params_.items():
    print(f"  {k:<18} = {v}")

results = pd.DataFrame(grid.cv_results_)
top5 = (results[['mean_test_score', 'std_test_score', 'params']]
        .sort_values('mean_test_score', ascending=False)
        .head(5)
        .reset_index(drop=True))
print("\nTop 5 configurations:")
print(top5.to_string())

best_rf = grid.best_estimator_

# Save so a runtime disconnect doesn't cost you the grid search
joblib.dump(best_rf, '/content/best_rf.joblib')

perm = permutation_importance(best_rf, X, y, n_repeats=10,
                              random_state=42, n_jobs=-1)

imp_df = pd.DataFrame({
    'feature': X.columns,
    'importance': perm.importances_mean,
    'std': perm.importances_std,
}).sort_values('importance', ascending=False)

print("\nPermutation importance:")
print(imp_df.to_string(index=False))

fig, ax = plt.subplots(figsize=(7, 3))
ax.barh(imp_df['feature'][::-1], imp_df['importance'][::-1],
        xerr=imp_df['std'][::-1], color='#534AB7')
ax.set_xlabel('Permutation importance (drop in R²)')
ax.set_title('Which features matter for predicting voltage')
plt.tight_layout()
plt.savefig('/content/perm_importance.png', dpi=120)
plt.show()

import shap

explainer = shap.TreeExplainer(rf)
shap_values = explainer.shap_values(X)

# Plot 1: global summary - ranking + direction
shap.summary_plot(shap_values, X)

# Plot 2: where in the curve each operating condition matters
for feat in ['pressure', 'relative_humidity', 'membrane_compression']:
    shap.dependence_plot(feat, shap_values, X,
                         interaction_index='current_density')

# =====================================================================
# Find the operating conditions that maximize power density
# =====================================================================
from scipy.optimize import differential_evolution

FEATURES = ['current_density', 'pressure', 'relative_humidity', 'membrane_compression']
bounds   = [(df[f].min(), df[f].max()) for f in FEATURES]

def neg_power(x):
    """Returns -power, because the optimizer minimizes."""
    v = best_rf.predict(np.array(x).reshape(1, -1))[0]
    return -(x[0] * v)              # power = current_density * voltage

result = differential_evolution(neg_power, bounds, seed=42, workers=-1)

print(f"\nMax power density: {-result.fun:.1f} mW/cm²")
print("At conditions:")
for name, val in zip(FEATURES, result.x):
    print(f"  {name:<22} = {val:.2f}")

# ---- show the polarization & power curve at the optimum --------------
i_sweep = np.linspace(bounds[0][0], bounds[0][1], 200)
X_sweep = np.column_stack([i_sweep,
                           np.full_like(i_sweep, result.x[1]),
                           np.full_like(i_sweep, result.x[2]),
                           np.full_like(i_sweep, result.x[3])])
v_sweep = best_rf.predict(X_sweep)
p_sweep = i_sweep * v_sweep

fig, ax1 = plt.subplots(figsize=(7, 4))
ax1.plot(i_sweep, v_sweep, color='#534AB7', label='Voltage')
ax1.set_xlabel('Current density (mA/cm²)')
ax1.set_ylabel('Voltage (V)', color='#534AB7')

ax2 = ax1.twinx()
ax2.plot(i_sweep, p_sweep, color='#C24A4A', label='Power')
ax2.set_ylabel('Power density (mW/cm²)', color='#C24A4A')
ax2.axvline(result.x[0], ls='--', color='gray', alpha=0.6)

plt.title(f"Optimum at P={result.x[1]:.0f}, RH={result.x[2]:.0f}, comp={result.x[3]:.1f}")
plt.tight_layout()
plt.savefig('/content/optimum_curve.png', dpi=120)
plt.show()